[book]
authors = ["adlsdztony"]
language = "en"
multilingual = true
src = "src"
title = "JoinUs Guide"


[rust]
edition = "2018"

[output.html]
smart-punctuation = true
mathjax-support = true
site-url = "/mdBook/"
git-repository-url = "https://github.com/EZ-HKU/join-us"
edit-url-template = "https://github.com/EZ-HKU/join-us/edit/main/{path}"

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
# "/format/config.html" = "configuration/index.html"

[output.html.multilingual]
default-language = "en"
languages = ["en", "zh"]